public import Declaration_Derivation_Diagnostics
public import Declaration_Derivation_Model

extension Declaration.Derivation {

    public struct Emitter: Sendable {

        public let contract: Declaration.GenerationContract

        public init(contract: Declaration.GenerationContract) {
            self.contract = contract
        }
    }
}

extension Declaration.Derivation.Emitter {

    public func memberDeclarations(
        for intermediateRepresentation: Declaration.IR
    ) throws(Declaration.Derivation.Diagnostic) -> [String] {
        let node = intermediateRepresentation.node
        guard contract.covers(node) else {
            throw Declaration.Derivation.Diagnostic(
                code: .unsupportedDeclarationKind,
                subject: node.name,
                detail: "the generation contract does not cover this declaration"
            )
        }
        var declarations: [String] = []
        switch node.kind {
        case .structure, .actor:
            declarations.append(try memberwiseInitializer(for: node))

        case .enumeration:
            declarations.append(caseNameAccessor(for: node))
        }
        declarations.append(provenanceMember())
        return declarations
    }

    public func emit(
        _ intermediateRepresentation: Declaration.IR
    ) throws(Declaration.Derivation.Diagnostic) -> Declaration.Derivation.RenderedFile {
        let node = intermediateRepresentation.node
        let members = try memberDeclarations(for: intermediateRepresentation)
        var lines: [String] = [
            "// \(contract.generatedFileName(for: node.name))",
            "// Generated by swift-declaration-derivation. Do not edit.",
            "// \(contract.provenance)",
            "",
            "extension \(node.name.text) {",
        ]
        for (index, member) in members.enumerated() {
            if index > 0 {
                lines.append("")
            }
            for memberLine in member.split(separator: "\n", omittingEmptySubsequences: false) {
                lines.append(memberLine.isEmpty ? "" : "    \(memberLine)")
            }
        }
        lines.append("}")
        lines.append("")
        let fileName = Declaration.Derivation.RenderedFile.FileName(
            contract.generatedFileName(for: node.name)
        )
        return Declaration.Derivation.RenderedFile(
            fileName: fileName,
            contents: lines.joined(separator: "\n")
        )
    }

    private func memberwiseInitializer(
        for node: Declaration.Node
    ) throws(Declaration.Derivation.Diagnostic) -> String {
        var parameters: [String] = []
        var assignments: [String] = []
        for member in node.members {
            if member.mutability == .constant, member.defaultValue != nil {

                continue
            }
            guard let typeReference = member.typeReference else {
                throw Declaration.Derivation.Diagnostic(
                    code: .malformedDeclaration,
                    subject: node.name,
                    detail: "stored member '\(member.name.text)' carries no type reference"
                )
            }
            var parameter = ""
            if let label = member.label, label.text != member.name.text {
                parameter += "\(label.text) "
            }
            parameter += "\(member.name.text): \(typeReference.text)"
            if let defaultValue = member.defaultValue {
                parameter += " = \(defaultValue.text)"
            }
            parameters.append(parameter)
            assignments.append("    self.\(member.name.text) = \(member.name.text)")
        }
        if parameters.isEmpty {
            return "public init() {}"
        }
        var lines: [String] = ["public init("]
        lines.append(parameters.map { "    \($0)" }.joined(separator: ",\n"))
        lines.append(") {")
        lines.append(contentsOf: assignments)
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    private func caseNameAccessor(for node: Declaration.Node) -> String {
        var lines: [String] = ["public var derivedCaseName: String {"]
        if node.members.isEmpty {
            lines.append("    switch self {}")
        } else {
            lines.append("    switch self {")
            for member in node.members {
                lines.append("    case .\(member.name.text): \"\(member.name.text)\"")
            }
            lines.append("    }")
        }
        lines.append("}")
        return lines.joined(separator: "\n")
    }

    private func provenanceMember() -> String {
        "public static var declarationDerivationProvenance: String { \"\(contract.provenance)\" }"
    }
}
