// Declaration.Derivation.Emitter.swift

public import DeclarationDerivationDiagnostics
public import DeclarationDerivationModel

extension Declaration.Derivation {
    /// The deterministic emitter of IR schema v1.
    ///
    /// Emission is a pure function of the analyzed IR and the generation
    /// contract: the same input renders byte-identically on every run. The
    /// emitter derives the v1 interface — a label- and default-preserving
    /// memberwise initializer for structures and actors, a stable case-name
    /// accessor for enumerations — plus the provenance member the contract
    /// mandates. It only ever renders files whose names the contract owns;
    /// handwritten declarations outside the contract are never touched.
    public struct Emitter: Sendable {
        public let contract: Declaration.GenerationContract

        public init(contract: Declaration.GenerationContract) {
            self.contract = contract
        }
    }
}

extension Declaration.Derivation.Emitter {

        /// The derived member declarations for an analyzed IR, in stable
        /// order, each rendered as canonical Swift source.
        public func memberDeclarations(
            for intermediateRepresentation: Declaration.IR
        ) throws(Declaration.Derivation.Diagnostic) -> [String] {
            let node = intermediateRepresentation.node
            guard contract.covers(node) else {
                throw Declaration.Derivation.Diagnostic(
                    code: .unsupportedDeclarationKind,
                    subject: node.name,
                    detail: "the generation contract does not cover this declaration"
                )
            }
            var declarations: [String] = []
            switch node.kind {
            case .structure, .actor:
                declarations.append(try memberwiseInitializer(for: node))
            case .enumeration:
                declarations.append(caseNameAccessor(for: node))
            }
            declarations.append(provenanceMember())
            return declarations
        }

        /// The complete rendered file for an analyzed IR: provenance header,
        /// then an extension of the declared type containing the derived
        /// members.
        public func emit(
            _ intermediateRepresentation: Declaration.IR
        ) throws(Declaration.Derivation.Diagnostic) -> Declaration.Derivation.RenderedFile {
            let node = intermediateRepresentation.node
            let members = try memberDeclarations(for: intermediateRepresentation)
            var lines: [String] = [
                "// \(contract.generatedFileName(for: node.name))",
                "// Generated by swift-declaration-derivation. Do not edit.",
                "// \(contract.provenance)",
                "",
                "extension \(node.name.text) {",
            ]
            for (index, member) in members.enumerated() {
                if index > 0 {
                    lines.append("")
                }
                for memberLine in member.split(separator: "\n", omittingEmptySubsequences: false) {
                    lines.append(memberLine.isEmpty ? "" : "    \(memberLine)")
                }
            }
            lines.append("}")
            lines.append("")
            return Declaration.Derivation.RenderedFile(
                fileName: Declaration.Derivation.RenderedFile.FileName(contract.generatedFileName(for: node.name)),
                contents: lines.joined(separator: "\n")
            )
        }

        // MARK: - Derived members

        private func memberwiseInitializer(
            for node: Declaration.Node
        ) throws(Declaration.Derivation.Diagnostic) -> String {
            var parameters: [String] = []
            var assignments: [String] = []
            for member in node.members {
                guard let typeReference = member.typeReference else {
                    throw Declaration.Derivation.Diagnostic(
                        code: .malformedDeclaration,
                        subject: node.name,
                        detail: "stored member '\(member.name.text)' carries no type reference"
                    )
                }
                var parameter = ""
                if let label = member.label, label.text != member.name.text {
                    parameter += "\(label.text) "
                }
                parameter += "\(member.name.text): \(typeReference.text)"
                if let defaultValue = member.defaultValue {
                    parameter += " = \(defaultValue.text)"
                }
                parameters.append(parameter)
                assignments.append("    self.\(member.name.text) = \(member.name.text)")
            }
            if parameters.isEmpty {
                return "public init() {}"
            }
            var lines: [String] = ["public init("]
            lines.append(parameters.map { "    \($0)" }.joined(separator: ",\n"))
            lines.append(") {")
            lines.append(contentsOf: assignments)
            lines.append("}")
            return lines.joined(separator: "\n")
        }

        private func caseNameAccessor(for node: Declaration.Node) -> String {
            var lines: [String] = ["public var derivedCaseName: String {"]
            if node.members.isEmpty {
                lines.append("    switch self {}")
            } else {
                lines.append("    switch self {")
                for member in node.members {
                    lines.append("    case .\(member.name.text): \"\(member.name.text)\"")
                }
                lines.append("    }")
            }
            lines.append("}")
            return lines.joined(separator: "\n")
        }

        private func provenanceMember() -> String {
            "public static var declarationDerivationProvenance: String { \"\(contract.provenance)\" }"
        }}
